### ISSUE TITLE
An error and some requests

### ISSUE THREAD

**Issue by ran88dom99** [XanderHorn/autoEDA#2]
error in every univar except histogram
#Error in match(x, table, nomatch = 0L) : 'match' requires vector arguments

always a huge spice at center. probably bc cut off values?

bins should be 200

bivariate needs black dots with blue density contours and a red loess and red dot at absolute center 

print( ggplot(ratingssummary,aes(x=get(col_name1),y=get(col_name2))) +
    geom_point(stat="identity", position="jitter", alpha=0.3, size=1)+ 
    geom_density2d(stat="density2d", position="identity") +
    xlab(col_name1) + ylab(col_name2) + geom_smooth(color="red"))

**Comment by XanderHorn** [comment]
Can you perhaps provide a sample of the data that you are working with that caused this issue?

**Comment by ran88dom99** [comment]
Oops. Density has to be in quotes "density". I am sorry. Still, about that spike at center of histograms density that almost certainly contains cut off values: sometimes its way too big.  QQplot does not seem to order vars so I just get a plot filld with green.

**Comment by XanderHorn** [comment]
Can you post a image of the plot that you mentioned as well as sample data?
