### ISSUE TITLE
plot title spelling

### ISSUE THREAD

**Issue by KnutJaegersberg** [XanderHorn/autoEDA#3]
Hi I like using your packages from time to time, 
in this one there is a tiny spelling error, which makes results look odd:
For the rest, very handy package to get a first glance at the data!

![Rplot](https://user-images.githubusercontent.com/17965169/57182833-9f6e2b00-6ea4-11e9-80aa-72eb1a8065d1.png)

**Comment by XanderHorn** [comment]
This has been fixed, thanks for posting.
